version: "3.8"
services:
  frontend:
    build: ./frontend
    ports:
      - 3000:3000
  backend:
    build: ./backend
    ports:
      - 3001:3001
  ws-db:
    image: mongo:3
    ports:
      - 27017:27017